# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
linters:
  default: standard
  enable:
    - gocritic
    - bodyclose
    - misspell
    - sloglint
    - sqlclosecheck
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    gofumpt:
      extra-rules: true
